export const BossType = {
  NONE: 0,
  WEAKEST: 1, //wave%5
  WEAK: 2, //wave%25
  MEDIUM: 3, //wave%100
  STRONG: 4, //wave%300
  STRONGEST: 5, //wave%1500
  GYM_LEADER_WEAKEST: 11,
  GYM_LEADER_WEAK: 12,
  GYM_LEADER_MEDIUM: 13,
  GYM_LEADER_STRONG: 14,
  GYM_LEADER_STRONGEST: 15,
  ELITE_FOUR_WEAKEST: 21,
  ELITE_FOUR_WEAK: 22,
  ELITE_FOUR_MEDIUM: 23,
  ELITE_FOUR_STRONG: 24,
  ELITE_FOUR_STRONGEST: 25,
  CHAMPION_WEAKEST: 31,
  CHAMPION_WEAK: 32,
  CHAMPION_MEDIUM: 33,
  CHAMPION_STRONG: 34,
  CHAMPION_STRONGEST: 35,
  RIVAL_WEAKEST: 41,
  RIVAL_WEAK: 42,
  RIVAL_MEDIUM: 43,
  RIVAL_STRONG: 44,
  RIVAL_STRONGEST: 45,
  LEGENDARY_WEAKEST: 51,
  LEGENDARY_WEAK: 52,
  LEGENDARY_MEDIUM: 53,
  LEGENDARY_STRONG: 54,
  LEGENDARY_STRONGEST: 55,
  OTHER: 61,
}