import { SpeciesId } from "./enums/species-id.js";

export const POKERUS_STARTER_COUNT = 5;
export const FRIENDSHIP_GAIN_FROM_BATTLE = 3;
/** The base amount of friendship gained from using a Rare Candy. */
export const FRIENDSHIP_GAIN_FROM_RARE_CANDY = 6;
/** The amount of friendship lost upon fainting. */
export const FRIENDSHIP_LOSS_FROM_FAINT = 5;
/** The minimum friendship value for enemy trainers at wave 1. (should be pokemon base friendship instead)*/
export const TRAINER_MIN_FRIENDSHIP = 50;
/** The wave at which enemy trainers reach the maximum friendship value of 255. */
export const TRAINER_MAX_FRIENDSHIP_WAVE = 145;

export const speciesStarterCosts = {
  [SpeciesId.BULBASAUR]: 3,
  [SpeciesId.CHARMANDER]: 3,
  [SpeciesId.SQUIRTLE]: 3,
  [SpeciesId.CATERPIE]: 2,
  [SpeciesId.WEEDLE]: 1,
  [SpeciesId.PIDGEY]: 1,
  [SpeciesId.RATTATA]: 1,
  [SpeciesId.SPEAROW]: 1,
  [SpeciesId.EKANS]: 2,
  [SpeciesId.PIKACHU]: 4,
  [SpeciesId.SANDSHREW]: 2,
  [SpeciesId.NIDORAN_F]: 3,
  [SpeciesId.NIDORAN_M]: 3,
  [SpeciesId.VULPIX]: 3,
  [SpeciesId.ZUBAT]: 3,
  [SpeciesId.ODDISH]: 3,
  [SpeciesId.PARAS]: 2,
  [SpeciesId.VENONAT]: 2,
  [SpeciesId.DIGLETT]: 2,
  [SpeciesId.MEOWTH]: 3,
  [SpeciesId.PSYDUCK]: 2,
  [SpeciesId.MANKEY]: 4,
  [SpeciesId.GROWLITHE]: 4,
  [SpeciesId.POLIWAG]: 2,
  [SpeciesId.ABRA]: 4,
  [SpeciesId.MACHOP]: 3,
  [SpeciesId.BELLSPROUT]: 2,
  [SpeciesId.TENTACOOL]: 3,
  [SpeciesId.GEODUDE]: 3,
  [SpeciesId.PONYTA]: 2,
  [SpeciesId.SLOWPOKE]: 3,
  [SpeciesId.MAGNEMITE]: 4,
  [SpeciesId.FARFETCHD]: 2,
  [SpeciesId.DODUO]: 3,
  [SpeciesId.SEEL]: 1,
  [SpeciesId.GRIMER]: 2,
  [SpeciesId.SHELLDER]: 5,
  [SpeciesId.GASTLY]: 4,
  [SpeciesId.ONIX]: 3,
  [SpeciesId.DROWZEE]: 2,
  [SpeciesId.KRABBY]: 3,
  [SpeciesId.VOLTORB]: 2,
  [SpeciesId.EXEGGCUTE]: 3,
  [SpeciesId.CUBONE]: 3,
  [SpeciesId.LICKITUNG]: 3,
  [SpeciesId.KOFFING]: 2,
  [SpeciesId.RHYHORN]: 4,
  [SpeciesId.TANGELA]: 3,
  [SpeciesId.KANGASKHAN]: 4,
  [SpeciesId.HORSEA]: 3,
  [SpeciesId.GOLDEEN]: 2,
  [SpeciesId.STARYU]: 3,
  [SpeciesId.SCYTHER]: 5,
  [SpeciesId.PINSIR]: 4,
  [SpeciesId.TAUROS]: 4,
  [SpeciesId.MAGIKARP]: 4,
  [SpeciesId.LAPRAS]: 4,
  [SpeciesId.DITTO]: 2,
  [SpeciesId.EEVEE]: 3,
  [SpeciesId.PORYGON]: 4,
  [SpeciesId.OMANYTE]: 3,
  [SpeciesId.KABUTO]: 3,
  [SpeciesId.AERODACTYL]: 5,
  [SpeciesId.ARTICUNO]: 5,
  [SpeciesId.ZAPDOS]: 6,
  [SpeciesId.MOLTRES]: 6,
  [SpeciesId.DRATINI]: 4,
  [SpeciesId.MEWTWO]: 8,
  [SpeciesId.MEW]: 5,
}